export const map = [
  "hwwwwwwwwwwwwwwwwwwwwwwwwwwwwh",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "h                            h",
  "hwwwwwwwwwwwwwwwwwwwwwwwwwwwwh",
];