export const map = [
  "hwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwh",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "h                                         h",
  "hwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwh",
];